//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AoC.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AoC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ......644............612.......254..638..............802.................................118.....................................317.691....
        ///.....*......321..176....+........&amp;...=...906........*.......=518................994..938.*.....579....35....155...........320...........$...
        ///...939.@225........*......................$........41......................./.....+......102....*.....*...............603....*.413=.........
        ///............470.128...288...+......442-.......191.....%....&amp;........360....218........ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Day3Input {
            get {
                return ResourceManager.GetString("Day3Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 12.......*..
        ///+.........34
        ///.......-12..
        ///..78........
        ///..*....60...
        ///78.........9
        ///.5.....23..$
        ///8...90*12...
        ///............
        ///2.2......12.
        ///.*.........*
        ///1.1..503+.56 ähnelt.
        /// </summary>
        internal static string Day3Test {
            get {
                return ResourceManager.GetString("Day3Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Card   1: 33 34 29 52 91  7 31 42  2  6 | 53 52  6 96 42 91  2 23  7 38 90 28 31 51  1 26 33 22 95 34 29 77 32 86  3
        ///Card   2: 63 86  6  5 95 17  7 72 62 76 | 26  6 86 68 49 57 30 63 80  5 96 84 42 19 53  7 87 78 70 74 15 17 64 16 44
        ///Card   3: 22 25  2 41 27 23  5  1 50 37 | 68 94 25  4 48 75 47 37 58 22 95 16 74 50 66 99 34 35 41 90  2 43 62  1 97
        ///Card   4: 98 43 31 15 77 60 25 66 19 26 | 59 54 43 19 36 25 31  5 44 76 98 93 40 60 66 47 28 65 56 26 10 15 67 77  3
        ///Card   5: 26 80 12 66 16 20 37 23 95 55  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Day4Input {
            get {
                return ResourceManager.GetString("Day4Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Card 1: 41 48 83 86 17 | 83 86  6 31 17  9 48 53
        ///Card 2: 13 32 20 16 61 | 61 30 68 82 17 32 24 19
        ///Card 3:  1 21 53 59 44 | 69 82 63 72 16 21 14  1
        ///Card 4: 41 92 73 84 69 | 59 84 76 51 58  5 54 83
        ///Card 5: 87 83 26 28 32 | 88 30 70 12 93 22 82 36
        ///Card 6: 31 18 13 56 72 | 74 77 10 23 35 67 36 11 ähnelt.
        /// </summary>
        internal static string Day4Test {
            get {
                return ResourceManager.GetString("Day4Test", resourceCulture);
            }
        }
    }
}
